/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package oop.assignment;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import oop.assignment.dao.productDAO;
import oop.assignment.dao.supplierDAO;
import oop.assignment.repository.ProductRepository;
import oop.assignment.repository.SupplierRepository;


public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    private ProductRepository productRepository;
    
    private SupplierRepository supplierRepository;
    
    private List<String> supplierNames = new ArrayList<>();

    private Map<String, Integer> supplierSelection = new HashMap<>();
    
    public MainFrame() {
        initComponents();
        productRepository = new ProductRepository();
        supplierRepository = new SupplierRepository();
        initSupplierSelection();
    }

    private void initSupplierSelection() {
        List<supplierDAO> suppliers = supplierRepository.getListSupplier();
        for (supplierDAO s : suppliers) {
            if (s.isIsActive() == false) {
                continue;
            }
            this.supplierNames.add(s.getName());
        }

        for (supplierDAO s : suppliers) {
            if (s.isIsActive() == false) {
                continue;
            }
            supplierSelection.put(s.getName(), s.getId());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane2 = new javax.swing.JTabbedPane();
        Products = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        txtSearch = new javax.swing.JTextField();
        jbtSearch = new javax.swing.JButton();
        jbtAll = new javax.swing.JButton();
        New = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        productTable = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        ID = new javax.swing.JLabel();
        jtxtID = new javax.swing.JTextField();
        Name = new javax.swing.JLabel();
        jtxtName = new javax.swing.JTextField();
        SKU = new javax.swing.JLabel();
        jtxtSKU = new javax.swing.JTextField();
        Supplier = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        Quantity = new javax.swing.JLabel();
        jtxtQuantity = new javax.swing.JTextField();
        Price = new javax.swing.JLabel();
        jtxtPrice = new javax.swing.JTextField();
        jbtCreate = new javax.swing.JButton();
        jbtUpdate = new javax.swing.JButton();
        jbtRemove = new javax.swing.JButton();
        jbtReset = new javax.swing.JButton();
        Suppliers = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        txtSearchSupplier = new javax.swing.JTextField();
        jbtSearchSupplier = new javax.swing.JButton();
        jbtAllSuplier = new javax.swing.JButton();
        jbtNewSupplier = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        supplierTable = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        SupplierID = new javax.swing.JLabel();
        jtxtSupplierID = new javax.swing.JTextField();
        SupplierName = new javax.swing.JLabel();
        jtxtSupplierName = new javax.swing.JTextField();
        SupplierPhone = new javax.swing.JLabel();
        jtxtSupplierPhone = new javax.swing.JTextField();
        SupplierAddress = new javax.swing.JLabel();
        jtxtSupplierAddress = new javax.swing.JTextField();
        jbtRemoveSupplier = new javax.swing.JButton();
        jbtUpdateSupplier = new javax.swing.JButton();
        jbtCreateSupplier = new javax.swing.JButton();
        jbtResetSupplier = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jbtSearch.setText("Search");
        jbtSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtSearchActionPerformed(evt);
            }
        });

        jbtAll.setText("All");
        jbtAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtAllActionPerformed(evt);
            }
        });

        New.setText("New");
        New.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtSearch)
                .addGap(18, 18, 18)
                .addComponent(jbtAll)
                .addGap(18, 18, 18)
                .addComponent(New)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtSearch)
                    .addComponent(jbtAll)
                    .addComponent(New))
                .addContainerGap())
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        productTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "SKU", "Supplier", "Quantity", "Price"
            }
        ));
        productTable.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                productTableAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        productTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                productTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(productTable);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 553, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 429, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        ID.setText("ID");

        jtxtID.setEnabled(false);

        Name.setText("Name");

        SKU.setText("SKU");

        Supplier.setText("Supplier");

        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        Quantity.setText("Quantity");

        Price.setText("Price");

        jbtCreate.setText("Create");
        jbtCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtCreateActionPerformed(evt);
            }
        });

        jbtUpdate.setText("Update");
        jbtUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtUpdateActionPerformed(evt);
            }
        });

        jbtRemove.setText("Remove");
        jbtRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtRemoveActionPerformed(evt);
            }
        });

        jbtReset.setText("Reset");
        jbtReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtResetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jbtRemove, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jbtUpdate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(Price, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Quantity, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE)
                            .addComponent(Supplier, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(SKU, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ID, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Name, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtxtID)
                            .addComponent(jtxtName)
                            .addComponent(jtxtSKU)
                            .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jtxtQuantity)
                            .addComponent(jtxtPrice)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jbtCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jbtReset, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jtxtID)
                    .addComponent(ID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jtxtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(Name, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SKU, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtSKU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Supplier, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Quantity, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Price, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtUpdate)
                    .addComponent(jbtRemove))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtCreate)
                    .addComponent(jbtReset))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout ProductsLayout = new javax.swing.GroupLayout(Products);
        Products.setLayout(ProductsLayout);
        ProductsLayout.setHorizontalGroup(
            ProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProductsLayout.createSequentialGroup()
                .addGroup(ProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ProductsLayout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        ProductsLayout.setVerticalGroup(
            ProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProductsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jTabbedPane2.addTab("Products", Products);

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txtSearchSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchSupplierActionPerformed(evt);
            }
        });

        jbtSearchSupplier.setText("Search");
        jbtSearchSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtSearchSupplierActionPerformed(evt);
            }
        });

        jbtAllSuplier.setText("All");
        jbtAllSuplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtAllSuplierActionPerformed(evt);
            }
        });

        jbtNewSupplier.setText("New");
        jbtNewSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtNewSupplierActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtSearchSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtSearchSupplier)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtAllSuplier)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtNewSupplier)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSearchSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtSearchSupplier)
                    .addComponent(jbtAllSuplier)
                    .addComponent(jbtNewSupplier))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        supplierTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Phone", "Address"
            }
        ));
        supplierTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                supplierTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(supplierTable);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 548, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        SupplierID.setText("ID");

        jtxtSupplierID.setEnabled(false);

        SupplierName.setText("Name");

        SupplierPhone.setText("Phone");

        SupplierAddress.setText("Address");

        jbtRemoveSupplier.setText("Remove");
        jbtRemoveSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtRemoveSupplierActionPerformed(evt);
            }
        });

        jbtUpdateSupplier.setText("Update");
        jbtUpdateSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtUpdateSupplierActionPerformed(evt);
            }
        });

        jbtCreateSupplier.setText("Create");
        jbtCreateSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtCreateSupplierActionPerformed(evt);
            }
        });

        jbtResetSupplier.setText("Reset");
        jbtResetSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtResetSupplierActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(SupplierAddress, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                            .addComponent(SupplierPhone, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(SupplierName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(SupplierID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtxtSupplierID)
                            .addComponent(jtxtSupplierName)
                            .addComponent(jtxtSupplierPhone)
                            .addComponent(jtxtSupplierAddress)))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jbtCreateSupplier, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbtRemoveSupplier, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jbtUpdateSupplier, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                            .addComponent(jbtResetSupplier, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SupplierID, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtSupplierID, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SupplierName, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtSupplierName, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(SupplierPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jtxtSupplierPhone)
                        .addGap(1, 1, 1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SupplierAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtSupplierAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(68, 68, 68)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jbtUpdateSupplier, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                    .addComponent(jbtRemoveSupplier, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(31, 31, 31)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtCreateSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtResetSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(128, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout SuppliersLayout = new javax.swing.GroupLayout(Suppliers);
        Suppliers.setLayout(SuppliersLayout);
        SuppliersLayout.setHorizontalGroup(
            SuppliersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SuppliersLayout.createSequentialGroup()
                .addGroup(SuppliersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SuppliersLayout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        SuppliersLayout.setVerticalGroup(
            SuppliersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SuppliersLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(SuppliersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jTabbedPane2.addTab("Suppliers", Suppliers);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane2)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
  
    
    private void NewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewActionPerformed
        // TODO add your handling code here:
        
        DefaultComboBoxModel comboBoxModel = new DefaultComboBoxModel(supplierNames.toArray());
        jComboBox1.setModel(comboBoxModel);
        jbtResetActionPerformed(evt);
    }//GEN-LAST:event_NewActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jbtAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtAllActionPerformed
        // TODO add your handling code here:
        List<productDAO> proList = productRepository.listProduct();
        showProductTable(proList);
    }//GEN-LAST:event_jbtAllActionPerformed

    private void jbtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtSearchActionPerformed
        // TODO add your handling code here:
        String searchTxt = txtSearch.getText();
        List<productDAO> proList = productRepository.searchProduct(searchTxt);
        showProductTable(proList);
    }//GEN-LAST:event_jbtSearchActionPerformed

    private void jbtCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtCreateActionPerformed
        // TODO add your handling code here:
        if (check()){
            String name = jtxtName.getText();
            String sku  = jtxtSKU.getText();
            int supplierID = supplierSelection.get(jComboBox1.getSelectedItem().toString());
            int qty = Integer.parseInt(jtxtQuantity.getText());
            double price = Double.parseDouble(jtxtPrice.getText());
        
            productDAO pDAO = new productDAO(name, sku, supplierID, qty, price);
            productRepository.createProduct(pDAO);
        
            List<productDAO> proList = productRepository.listProduct();
            showProductTable(proList);
        }
        
    }//GEN-LAST:event_jbtCreateActionPerformed

    private void jbtResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtResetActionPerformed
        // TODO add your handling code here:
        jtxtName.setText("");
        jtxtSKU.setText("");
        jComboBox1.setSelectedIndex(0);
        jtxtQuantity.setText("");
        jtxtPrice.setText("");
    }//GEN-LAST:event_jbtResetActionPerformed

    
    private void productTableAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_productTableAncestorAdded
        // TODO add your handling code here:
        
    }//GEN-LAST:event_productTableAncestorAdded

    private void jbtUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtUpdateActionPerformed
        // TODO add your handling code here:
        if (check()){
            int id = Integer.parseInt(jtxtID.getText());
            String name = jtxtName.getText();
            String sku  = jtxtSKU.getText();
            int supplierID = supplierSelection.get(jComboBox1.getSelectedItem().toString());
            int qty = Integer.parseInt(jtxtQuantity.getText());
            double price = Double.parseDouble(jtxtPrice.getText());
        
            productDAO pDAO = new productDAO(id,name, sku, supplierID, qty, price);
            productRepository.updateProduct(pDAO);
        
            List<productDAO> proList = productRepository.listProduct();
            showProductTable(proList);
        }
    }//GEN-LAST:event_jbtUpdateActionPerformed

    private void productTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_productTableMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel)productTable.getModel();
        int row= productTable.getSelectedRow();
        
        jtxtID.setText(model.getValueAt(row, 0).toString());
        jtxtName.setText(model.getValueAt(row, 1).toString());
        jtxtSKU.setText(model.getValueAt(row,2).toString());
        String supplierSelectName  = model.getValueAt(row, 3).toString();
        jtxtQuantity.setText(model.getValueAt(row, 4).toString());
        jtxtPrice.setText(model.getValueAt(row, 5).toString());
        
        DefaultComboBoxModel comboBoxModel = new DefaultComboBoxModel(supplierNames.toArray());
        jComboBox1.setModel(comboBoxModel);
        jComboBox1.setSelectedItem(supplierSelectName);
    }//GEN-LAST:event_productTableMouseClicked

    private void jbtRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtRemoveActionPerformed
        // TODO add your handling code here:
        int id = Integer.parseInt(jtxtID.getText());
        productRepository.removeProduct(id);
        
        List<productDAO> proList = productRepository.listProduct();
        showProductTable(proList);
    }//GEN-LAST:event_jbtRemoveActionPerformed

    private void txtSearchSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchSupplierActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtSearchSupplierActionPerformed

    private void jbtRemoveSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtRemoveSupplierActionPerformed
        // TODO add your handling code here:
        int id = Integer.parseInt(jtxtSupplierID.getText());
        supplierRepository.removeSupplier(id);
        
        List<supplierDAO> suppList = supplierRepository.listSupplier();
        showSupplierTable(suppList);
    }//GEN-LAST:event_jbtRemoveSupplierActionPerformed

    private void jbtSearchSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtSearchSupplierActionPerformed
        // TODO add your handling code here:
        String searchTxt = txtSearchSupplier.getText();
        List<supplierDAO> suppList = supplierRepository.searchSupplier(searchTxt);
        showSupplierTable(suppList);
    }//GEN-LAST:event_jbtSearchSupplierActionPerformed

    private void jbtAllSuplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtAllSuplierActionPerformed
        // TODO add your handling code here:
        List<supplierDAO> suppList = supplierRepository.listSupplier();
        showSupplierTable(suppList);
    }//GEN-LAST:event_jbtAllSuplierActionPerformed

    private void jbtCreateSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtCreateSupplierActionPerformed
        // TODO add your handling code here:
        //int id = Integer.parseInt(jtxtSupplierID.getText());
        String name = jtxtSupplierName.getText();
        String phone = jtxtSupplierPhone.getText();
        String address = jtxtSupplierAddress.getText();
        
        supplierDAO sDAO = new supplierDAO(name, phone, address);
        supplierRepository.createSupplier(sDAO);
        
        List<supplierDAO> suppList = supplierRepository.listSupplier();
        showSupplierTable(suppList);
    }//GEN-LAST:event_jbtCreateSupplierActionPerformed

    private void jbtNewSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtNewSupplierActionPerformed
        // TODO add your handling code here:
        jbtResetSupplierActionPerformed(evt);
    }//GEN-LAST:event_jbtNewSupplierActionPerformed

    private void jbtResetSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtResetSupplierActionPerformed
        // TODO add your handling code here:
        jtxtSupplierID.setText("");
        jtxtSupplierName.setText("");
        jtxtSupplierPhone.setText("");
        jtxtSupplierAddress.setText("");
    }//GEN-LAST:event_jbtResetSupplierActionPerformed

    private void supplierTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_supplierTableMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel)supplierTable.getModel();
        int row = supplierTable.getSelectedRow();
        
        jtxtSupplierID.setText(model.getValueAt(row, 0).toString());
        jtxtSupplierName.setText(model.getValueAt(row, 1).toString());
        jtxtSupplierPhone.setText(model.getValueAt(row, 2).toString());
        jtxtSupplierAddress.setText(model.getValueAt(row, 3).toString());
        
    }//GEN-LAST:event_supplierTableMouseClicked

    private void jbtUpdateSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtUpdateSupplierActionPerformed
        // TODO add your handling code here:
        int id = Integer.parseInt(jtxtSupplierID.getText());
        String name = jtxtSupplierName.getText();
        String phone = jtxtSupplierPhone.getText();
        String address = jtxtSupplierAddress.getText();
        
        supplierDAO sDAO = new supplierDAO(id,name, phone, address);
        supplierRepository.updateSupplier(sDAO);
        
        List<supplierDAO> suppList = supplierRepository.listSupplier();
        showSupplierTable(suppList);
    }//GEN-LAST:event_jbtUpdateSupplierActionPerformed
   
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ID;
    private javax.swing.JLabel Name;
    private javax.swing.JButton New;
    private javax.swing.JLabel Price;
    private javax.swing.JPanel Products;
    private javax.swing.JLabel Quantity;
    private javax.swing.JLabel SKU;
    private javax.swing.JLabel Supplier;
    private javax.swing.JLabel SupplierAddress;
    private javax.swing.JLabel SupplierID;
    private javax.swing.JLabel SupplierName;
    private javax.swing.JLabel SupplierPhone;
    private javax.swing.JPanel Suppliers;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JButton jbtAll;
    private javax.swing.JButton jbtAllSuplier;
    private javax.swing.JButton jbtCreate;
    private javax.swing.JButton jbtCreateSupplier;
    private javax.swing.JButton jbtNewSupplier;
    private javax.swing.JButton jbtRemove;
    private javax.swing.JButton jbtRemoveSupplier;
    private javax.swing.JButton jbtReset;
    private javax.swing.JButton jbtResetSupplier;
    private javax.swing.JButton jbtSearch;
    private javax.swing.JButton jbtSearchSupplier;
    private javax.swing.JButton jbtUpdate;
    private javax.swing.JButton jbtUpdateSupplier;
    private javax.swing.JTextField jtxtID;
    private javax.swing.JTextField jtxtName;
    private javax.swing.JTextField jtxtPrice;
    private javax.swing.JTextField jtxtQuantity;
    private javax.swing.JTextField jtxtSKU;
    private javax.swing.JTextField jtxtSupplierAddress;
    private javax.swing.JTextField jtxtSupplierID;
    private javax.swing.JTextField jtxtSupplierName;
    private javax.swing.JTextField jtxtSupplierPhone;
    private javax.swing.JTable productTable;
    private javax.swing.JTable supplierTable;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtSearchSupplier;
    // End of variables declaration//GEN-END:variables

    private void showProductTable(List<productDAO> proList) {
        DefaultTableModel model = (DefaultTableModel)productTable.getModel();
        model.setRowCount(0);
        for(productDAO product : proList){
            model.addRow(new Object[]{product.getId(),product.getName(),product.getSku(),product.getSupplierName(),
                                      product.getQuantity(),product.getPrice()});
        }
        jPanel1.revalidate();
        jPanel1.repaint();
    }
    
    private void showSupplierTable(List<supplierDAO> suppList){
        DefaultTableModel model = (DefaultTableModel)supplierTable.getModel();
        model.setRowCount(0);
        for (supplierDAO supplier : suppList){
            model.addRow(new Object[]{supplier.getId(),supplier.getName(),supplier.getPhone(),supplier.getAddress()});
        }
        jPanel4.revalidate();
        jPanel4.repaint();
    }
    
    private boolean check(){
        if (jtxtName.getText().equals("")){
            JOptionPane.showMessageDialog(this, "chua nhap ten");
            jtxtName.requestFocus();
            return false;
        }
        
        if (jtxtSKU.getText().equals("")){
            JOptionPane.showMessageDialog(this,"chua nhap ma SKU");
            jtxtSKU.requestFocus();
            return false;
        }
        
        if (jtxtQuantity.getText().equals("")){
            JOptionPane.showMessageDialog(this,"chua nhap so luong");
            jtxtQuantity.requestFocus();
            return false;
        }
        
        if (jtxtPrice.getText().equals("")){
            JOptionPane.showMessageDialog(this,"chua nhap gia");
            jtxtPrice.requestFocus();
            return false;
        }
        return true;
    }
    
}
